apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
 name: astj-eks-test-cluster
 region: ap-northeast-1
 version: "1.18"

nodeGroups:
  - name: ec2Group
    instanceType: m5.large
    desiredCapacity: 1

fargateProfiles:
  - name: fargeteProfile
    selectors:
      - namespace: fargate
