apiVersion: v1
kind: Pod
metadata:
  name: agent
  labels:
    app: agent
spec:
  serviceAccountName: mackerel-container-agent-sa
  containers:
  - name: nginx
    image: nginx:1.17-alpine
    imagePullPolicy: Never
  - name: mackerel-container-agent
    image: ${IMAGE_NAME}
    imagePullPolicy: Never
    resources:
      limits:
        memory: 128Mi
        cpu: 3
      requests:
        cpu: 2
    env:
      - name: MACKEREL_CONTAINER_PLATFORM
        value: kubernetes
      - name: MACKEREL_APIKEY
        valueFrom:
          secretKeyRef:
            name: mackerel-container-agent
            key: MACKEREL_APIKEY
      - name: MACKEREL_KUBERNETES_KUBELET_HOST
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      - name: MACKEREL_KUBERNETES_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: MACKEREL_KUBERNETES_POD_NAME
        valueFrom:
         fieldRef:
            fieldPath: metadata.name
      - name: MACKEREL_KUBERNETES_NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: MACKEREL_KUBERNETES_KUBELET_READ_ONLY_PORT
        value: "0"
      - name: MACKEREL_KUBERNETES_KUBELET_INSECURE_TLS
        value: "true"
